[toolchain]
rust_version = "1.68.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
mycontract = "G282eaMza7v7527pDjt4yAA4FzuFZsSnJRSPuZFerCz6"

[programs.devnet]
mycontract = "G282eaMza7v7527pDjt4yAA4FzuFZsSnJRSPuZFerCz6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/huynh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.js"
